name: Playwright Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t playwright-tests:latest .

      - name: Run Playwright tests
        id: run-tests
        continue-on-error: true
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          API_USERNAME: ${{ secrets.API_USERNAME }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: |
          docker run --mount type=bind,source="$(pwd)",target=/app \
          -e API_BASE_URL -e API_USERNAME -e API_PASSWORD -e CI=true \
          playwright-tests:latest /bin/bash -c "npm install && PLAYWRIGHT_HTML_REPORT=/app/playwright-report npm run tests:all"
          
          echo "EXIT_CODE=$?" >> $GITHUB_ENV
          echo "Tests exit code: $?"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Deploy report to GitHub Pages
        if: steps.run-tests.outcome != 'cancelled' && steps.run-tests.outcome != 'skipped'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHUB_PAGES_TOKEN }}
          publish_dir: ./playwright-report
          keep_files: false
          force_orphan: true