name: Playwright Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t playwright-tests:latest .

      - name: Run Playwright tests
        run: |
          docker run --mount type=bind,source="$(pwd)",target=/app playwright-tests:latest /bin/bash -c "npm install && PLAYWRIGHT_HTML_REPORT=/app/playwright-report npm run tests:all"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Deploy report to GitHub Pages
        if: ${{ success() }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GHUB_PAGES_TOKEN }}
          publish_dir: ./playwright-report
          keep_files: false
          force_orphan: true